module.exports.error_messages = {
    interpreter:{
        emit_functions:{
            unlock_functions:{
                parameter_error:"",
                signal_unlocking_error:""
            },
            check_sig:{
                parameter_error:"",
                sig_always_checked:"",
                sig_result_not_correct:"",
                signal_unlocking_error:"",
                finally_unlocked_error:"",
            },
            add_verify_key:{
                parameter_error:"",
                data_type_error:"",
                public_key_adding_error:"",

            },
            add_verify_key_and_check_sigs:{
                parameter_error:"",
                minimum_keys_available:"",
                data_type_error:"",
                key_adding_error:"",
                sig_check_error:"",
                signal_unlocking_error:"",
                finally_unlocked_error:""
            },
            set_n_of_m_signatures:{
                parameter_error:"",
                invalid_parameter:"",
                invalid_number:"",
                not_entrought_public_keys:"",
                invalid_signatures_seted:"",
            },
            abort:{
                parameter_error:"",
            },
            push_to_y:{
                parameter_error:"",
                to_small_items:"",
            },
            check_lock_verify_time:{
                parameter_error:"",
                invalid_parameter:"",
                invalid_number_type:""
            },
            check_lock_block_time:{
                parameter_error:"",
                invalid_parameter:"",
                invalid_number_type:""
            },
            unlocking_script_hash:{
                parameter_error:"",
                invalid_parameter:"",
                invalid_hex_str_size:"",
            },
            er_signers:{
                parameter_error:"",
                max_parameter:"",
                public_key_type_error:"",
                used_key_error:""
            },
            unlock_then_eq_sig:{
                parameter_error:"",
                is_finally_true:"",
                signal_unlock_error:"",
            },
            exit:{
                parameter_error:""
            },
            parren_cube_error:"",
            unkown_function:""
        },
        reading_functions:{
            altchain_read:{
                bitcoin:{
                    invalid_len:"",
                    reading_error:""
                },
                ethereum:{
                    invalid_len:"",
                    reading_error:""
                },
                unkown_address_type:""
            },
            pk_read:{
                secp256k1_schnorr:{
                    invalid_len:"",
                },
                curve25519_schnorr:{
                    invalid_len:"",
                },
                bls12:{
                    invalid_len:"",
                },
                invalid_key_type:""
            }
        },
        if:{
            invalid_operations:"",
            invalid_dtype:"",
            unkown_operation:"",
            code_block_error:"",
            invalid_y_stack:"",
            invalid_if_stack:"",
            to_many_code_blocks:""
        },
        else:{
            to_many_code_blocks:"",
            code_block_run:"",
            code_run_error:""
        },
        value_functions:{
            parren_cube_interpreting_error:"",
            op_is_one_signer:{
                invalid_parameter:"",
            },
            sha256d:{
                invalid_parameter:""
            },
            sha3_256:{
                invalid_parameter:""
            },
            swifty_h_256:{
                invalid_parameter:""
            },
            pop_from_y:{
                invalid_parameter:""
            },
            total_sigs:{
                invalid_parameter:""
            },
            last_block_hash:{
                invalid_parameter:""
            },
            current_block_diff:{
                invalid_parameter:""
            },
            op_lock_script:{
                invalid_parameter:""
            },
            unlocking_script_hash:{
                invalid_parameter:""
            },
            current_block_hight:{
                invalid_parameter:""
            },
            eq_signers:{
                invalid_parameter:""
            },
            unkown_function:"",
            exception:""
        }
    }
};